project:
  type: website

website:
  title: "My Notes"
  image: images/barcelona.jpg
  site-url: "https://orion-lang.github.io/aiml"
  
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Linear Classifier"
        href: classifier.qmd   # only one topic for now

format:
  html:
    theme: cerulean
    toc: true
    number-sections: true
    html-math-method: katex
    page-layout: full
    highlight-style: vim-dark
    code-line-numbers: true
    css: styles.scss